Repository prgrms-web-devcourse-final-project/WEB1_2_TravelMaker_FE, pull requests merged in 2024-11, with the labels that each got.

#8 [main]: 메인 페이지 구성
  .prettierignore
  .storybook/preview.ts
  .storybook/preview.tsx
  eslint.config.js
  public/mockServiceWorker.js
  src/common/styles/Empty.tsx
  src/common/styles/theme.ts
  src/components/card/MyPlannerCard.stories.tsx
  src/components/card/MyPlannerCard.tsx
  src/components/cardList/MyPlannerCardList.stories.tsx
  src/components/cardList/MyPlannerCardList.tsx
  src/components/field/ActionLabel.stories.tsx
  src/components/field/Clickable.stories.tsx
  src/components/field/FormField.tsx
  src/components/field/Input.stories.tsx
  src/components/field/Label.stories.tsx
  src/components/field/baseArgTypes.ts
  src/components/icons/Copy.tsx
  src/components/icons/Date.tsx
  src/components/icons/Plane.tsx
Labels: feature

#10 [my] : 마이페이지 구성
  public/vite.svg
  src/components/header/Header.stories.ts
  src/components/header/Header.tsx
  src/components/header/Logo.tsx
  src/components/profile/CameraIcon.tsx
  src/components/profile/EditIcon.tsx
  src/components/profile/Profile.stories.ts
  src/components/profile/Profile.tsx
  src/components/profile/ProfileImage.tsx
Labels: feature

#9 [login]: 로그인 페이지 구성
  public/mockServiceWorker.js
  src/assets/fonts/icons/Google.svg
  src/components/assets/Icon.tsx
  src/components/assets/Icon1.tsx
  src/components/assets/LargeLogo.tsx
  src/components/button/Button.stories.tsx
  src/components/button/Button.tsx
  src/components/stories/Button.stories.ts
  src/components/stories/Button.tsx
  src/components/stories/Configure.mdx
  src/components/stories/Header.tsx
  src/components/stories/assets/accessibility.png
  src/components/stories/assets/accessibility.svg
  src/components/stories/assets/addon-library.png
  src/components/stories/assets/assets.png
  src/components/stories/assets/avif-test-image.avif
  src/components/stories/assets/context.png
  src/components/stories/assets/discord.svg
  src/components/stories/assets/docs.png
  src/components/stories/assets/figma-plugin.png
  src/components/stories/assets/github.svg
  src/components/stories/assets/share.png
  src/components/stories/assets/styling.png
  src/components/stories/assets/testing.png
  src/components/stories/assets/theming.png
  src/components/stories/assets/tutorials.svg
  src/components/stories/assets/youtube.svg
  src/components/stories/button.css
  src/pages/Login/index.tsx
Labels: feature

#16 [login]: 로그인 페이지 구성
  src/components/button/Button.stories.tsx
  src/components/button/Button.tsx
  src/pages/Login/index.tsx
Labels: design

#14 [main]: 메인 페이지 구성
  src/common/styles/theme.ts
  src/common/utils/calcByPercent.ts
  src/components/button/Button.stories.tsx
  src/components/button/Button.tsx
  src/components/card/MyPlannerCard.tsx
  src/components/card/StartPlannerCard.stories.tsx
  src/components/card/StartPlannerCard.tsx
  src/components/divider/Divider.stories.tsx
  src/components/divider/Divider.tsx
  src/components/field/FormField.tsx
  src/pages/Main/index.tsx
Labels: feature

#19 [schedule]: 일정관리 컴포넌트 구현
  src/components/assets/icons/CheckIcon.tsx
  src/components/assets/icons/CloseIcon.tsx
  src/components/assets/icons/NextIcon.tsx
  src/components/assets/icons/PreviousIcon.tsx
  src/components/assets/images/HorisontalLogo.tsx
  src/components/button/Button.stories.tsx
  src/components/button/PlanButtons.stories.tsx
  src/components/button/PlanButtons.tsx
  src/components/button/ScheduleBar.stories.tsx
  src/components/button/ScheduleBar.tsx
  src/components/button/mockSchedule.ts
  src/components/card/InfoCard.stories.tsx
  src/components/card/InfoCard.tsx
  src/components/card/RouteCard.stories.tsx
  src/components/card/RouteCard.tsx
  src/components/cardList/RouteCardList.stories.tsx
  src/components/cardList/RouteCardList.tsx
  src/components/section/ScheduleManager.stories.tsx
  src/components/section/ScheduleManager.tsx
  src/pages/Login/index.tsx
Labels: feature

#20 [chat]: 채팅 컴포넌트 구현
  .storybook/preview-head.html
  eslint.config.js
  package.json
  src/common/styles/Empty.tsx
  src/common/styles/EmptyBox.tsx
  src/common/styles/GlobalStyle.tsx
  src/common/styles/circleStyle.ts
  src/common/styles/theme.ts
  src/common/utils/calculateProportionalSize.ts
  src/common/utils/extractNumber.ts
  src/components/assets/icons/CloseIcon.tsx
  src/components/assets/icons/HostIcon.tsx
  src/components/assets/icons/KakaoIcon.tsx
  src/components/assets/icons/Send.tsx
  src/components/assets/images/LargeLogo.tsx
  src/components/button/Button.stories.tsx
  src/components/card/MyPlannerCard.tsx
  src/components/chat/Chat.stories.tsx
  src/components/chat/Chat.tsx
  src/components/chat/ChatInfoBar.stories.tsx
  src/components/chat/ChatInfoBar.tsx
  src/components/chat/ChatInput.stories.tsx
  src/components/chat/ChatInput.tsx
  src/components/chat/ChatList.stories.tsx
  src/components/chat/ChatList.tsx
  src/components/chat/ChatMessage.stories.tsx
  src/components/chat/ChatMessage.tsx
  src/components/chat/ChatProfile.stories.tsx
  src/components/chat/ChatProfile.tsx
  src/components/chat/ChatSubmitter.tsx
Labels: feature, chore

#22 [map]: 지도 컴포넌트 구현
  package-lock.json
  package.json
  src/components/assets/icons/EditIcon.tsx
  src/components/assets/icons/PlusIcon.tsx
  src/components/assets/icons/SearchIcon.tsx
  src/components/assets/icons/ZoomMinusIcon.tsx
  src/components/assets/icons/ZoomPlusIcon.tsx
  src/components/assets/images/ConfirmedMarkerImage.tsx
  src/components/assets/images/DefaultImage.svg
  src/components/assets/images/NormalMarkerImage.tsx
  src/components/assets/images/ProfileImage.tsx
  src/components/assets/images/SmallPing.tsx
  src/components/confirmedmarker/ConfirmedMarker.stories.tsx
  src/components/confirmedmarker/ConfirmedMarker.tsx
  src/components/header/Header.stories.tsx
  src/components/header/Header.tsx
  src/components/markerdetails/NormalMarkerDetails.stories.tsx
  src/components/markerdetails/NormalMarkerDetails.tsx
  src/components/more/MoreButton.stories.tsx
  src/components/more/MoreButton.tsx
  src/components/normalmarker/NormalMarker.stories.tsx
  src/components/normalmarker/NormalMarker.tsx
  src/components/profile/Profile.stories.tsx
  src/components/profile/Profile.tsx
  src/components/search/SearchBar.stories.tsx
  src/components/search/SearchBar.tsx
  src/components/searchresultcard/SearchResultCard.stories.tsx
  src/components/searchresultcard/SearchResultCard.tsx
  src/components/searchresultlist/SearchResultList.stories.tsx
  src/components/searchresultlist/SearchResultList.tsx
  src/components/zoomscreen/ZoomScreen.stories.tsx
  src/components/zoomscreen/ZoomScreen.tsx
  src/main.tsx
  src/pages/My/index.tsx
  src/pages/Planner/components/MapComponent.tsx
  src/pages/Planner/index.tsx
Labels: feature

#27 [map]: 지도 컴포넌트 수정
  src/components/cardList/MyPlannerCardList.tsx
Labels: fix

#26 [config] tailwind 라이브러리 삭제 (#1)
  README.md
  package-lock.json
  package.json
  postcss.config.js
  src/common/styles/GlobalStyle.tsx
  src/common/styles/tailwind.css
  tailwind.config.js
Labels: chore
