Repository prgrms-web-devcourse-final-project/WEB1_2_TravelMaker_FE, pull requests merged in 2024-12, with the labels that each got.

#32 [modal] 플래너 모달 컴포넌트
  package-lock.json
  package.json
  src/components/field/ActionLabel.stories.tsx
  src/components/field/Clickable.stories.tsx
  src/components/field/FormField.tsx
  src/components/field/Input.stories.tsx
  src/components/field/Label.stories.tsx
  src/components/field/baseArgTypes.ts
  src/components/modal/Config.stories.tsx
  src/components/modal/Confirm.stories.tsx
  src/components/modal/Entry.stories.tsx
  src/components/modal/Header.stories.tsx
  src/components/modal/Modal.tsx
  src/components/modal/Share.stories.tsx
  src/components/modal/headerArgTypes.ts
Labels: feature

#34 [map]: 지도 검색 API 연결
  package-lock.json
  package.json
  src/components/field/ActionLabel.stories.tsx
  src/components/field/Clickable.stories.tsx
  src/components/field/FormField.tsx
  src/components/field/Input.stories.tsx
  src/components/field/Label.stories.tsx
  src/components/field/baseArgTypes.ts
  src/components/markerdetails/NormalMarkerDetails.tsx
  src/components/modal/Config.stories.tsx
  src/components/modal/Confirm.stories.tsx
  src/components/modal/Entry.stories.tsx
  src/components/modal/Header.stories.tsx
  src/components/modal/Modal.tsx
  src/components/modal/Share.stories.tsx
  src/components/modal/headerArgTypes.ts
  src/components/searchresultcard/SearchResultCard.stories.tsx
  src/components/searchresultcard/SearchResultCard.tsx
  src/components/searchresultlist/SearchResultList.stories.tsx
  src/components/searchresultlist/SearchResultList.tsx
  src/pages/Planner/components/MapComponent.tsx
Labels: feature

#36 [landing]: 랜딩페이지 구현
  src/pages/Landing/imgs/LandingFifth.svg
  src/pages/Landing/imgs/LandingFirst.svg
  src/pages/Landing/imgs/LandingFourth.svg
  src/pages/Landing/imgs/LandingSecond.svg
  src/pages/Landing/imgs/LandingThird.svg
  src/pages/Landing/index.tsx
  src/pages/Login/index.tsx
  src/pages/index.ts
  src/routes/index.tsx
Labels: feature

#37 [main, chat]: 반응형 처리
  src/common/hooks/useWindowSize.ts
  src/common/styles/EmptyBox.tsx
  src/common/styles/GlobalStyle.tsx
  src/common/styles/ThemeProvider.tsx
  src/common/styles/hideScrollbar.ts
  src/common/styles/theme.ts
  src/common/utils/calculateProportionalSize.ts
  src/common/utils/createResponsiveCalculator.ts
  src/common/utils/scaleByContainer.ts
  src/components/assets/icons/GoogleIcon.tsx
  src/components/assets/icons/KakaoIcon.tsx
  src/components/assets/icons/Plane.tsx
  src/components/button/Button.stories.tsx
  src/components/button/Button.tsx
  src/components/card/InfoCard.tsx
  src/components/card/MyPlannerCard.tsx
  src/components/card/RouteCard.tsx
  src/components/card/StartPlannerCard.tsx
  src/components/cardList/MyPlannerCardList.tsx
  src/components/chat/Chat.tsx
  src/components/chat/ChatInfoBar.tsx
  src/components/chat/ChatInput.tsx
  src/components/chat/ChatList.tsx
  src/components/chat/ChatMessage.tsx
  src/components/chat/ChatProfile.tsx
  src/components/chat/ChatSubmitter.tsx
  src/components/field/FormField.tsx
  src/pages/Main/index.tsx
Labels: design, refactor

#40 [login]: 구글 로그인 구현
  src/pages/Login/LoginApi.tsx
  src/pages/Login/index.tsx
Labels: feature

#41 [map]: 지도 장소 API 추가 연결
  src/components/assets/images/NoImage.svg
  src/components/markerdetails/NormalMarkerDetails.tsx
  src/components/searchresultlist/SearchResultList.tsx
  src/pages/Planner/components/MapComponent.tsx
Labels: feature

#43 [map]: 장소 API 수정
  src/components/confirmedmarker/ConfirmedMarker.tsx
  src/components/normalmarker/NormalMarker.tsx
  src/components/search/SearchBar.tsx
  src/pages/Planner/components/MapComponent.tsx
Labels: fix

#44 [main] 네비게이터 가드 & 메인페이지 레이어 계층 분리
  src/api/fetch.ts
  src/common/hooks/useTypedNavigate.ts
  src/common/hooks/useTypedParams.ts
  src/components/button/Button.tsx
  src/components/card/StartPlannerCard.tsx
  src/components/debug/TokenCookieManager.tsx
  src/components/debug/withDevOnly.tsx
  src/pages/Main/containers/MyPlannerCardListContainer.tsx
  src/pages/Main/containers/StartPlannerCardContainer.tsx
  src/pages/Main/index.tsx
  src/pages/Modal/RoomCreateModal.tsx
  src/pages/Modal/RoomEnterModal.tsx
  src/pages/Modal/index.ts
  src/routes/index.tsx
  src/routes/type.ts
  vite.config.ts
Labels: feature

#45 [schedule]: 일정관리 반응형 설정 및 스타일 수정
  src/components/button/ScheduleBar.tsx
  src/components/button/mockSchedule.ts
  src/components/card/RouteCard.tsx
  src/components/cardList/RouteCardList.tsx
  src/components/section/ScheduleManager.tsx
  src/pages/Planner/index.tsx
Labels: design

#46 [map]: 반응형 처리
  src/common/styles/GlobalStyle.tsx
  src/components/assets/icons/PlusIcon.svg
  src/components/assets/icons/PlusIcon.tsx
  src/components/assets/icons/SearchIcon.svg
  src/components/assets/icons/SearchIcon.tsx
  src/components/assets/icons/ZoomMinusIcon.svg
  src/components/assets/icons/ZoomMinusIcon.tsx
  src/components/assets/icons/ZoomPlusIcon.svg
  src/components/assets/icons/ZoomPlusIcon.tsx
  src/components/assets/images/ConfirmedMarkerImage.svg
  src/components/assets/images/ConfirmedMarkerImage.tsx
  src/components/assets/images/NormalMarkerImage.svg
  src/components/assets/images/NormalMarkerImage.tsx
  src/components/assets/images/SmallPing.svg
  src/components/assets/images/SmallPing.tsx
  src/components/chat/Chat.tsx
  src/components/chat/ChatSubmitter.tsx
  src/components/confirmedmarker/ConfirmedMarker.tsx
  src/components/markerdetails/NormalMarkerDetails.tsx
  src/components/more/MoreButton.tsx
  src/components/normalmarker/NormalMarker.tsx
  src/components/search/SearchBar.tsx
  src/components/searchresultcard/SearchResultCard.tsx
  src/components/searchresultlist/SearchResultList.tsx
  src/components/zoomscreen/ZoomScreen.tsx
  src/pages/Planner/components/MapComponent.tsx
Labels: design

#48 [login, planner]: 로그인 기능 변경, 스케줄러 반응형 수정, 설정 버튼 구성
  package-lock.json
  public/mockServiceWorker.js
  src/api/fetch.ts
  src/components/assets/icons/Settings.svg
  src/components/button/PlanButtons.tsx
  src/components/button/ScheduleBar.tsx
  src/components/button/SettingButton.stories.tsx
  src/components/button/SettingButton.tsx
  src/components/card/RouteCard.tsx
  src/components/cardList/RouteCardList.tsx
  src/components/chat/ChatMessage.tsx
  src/components/section/ScheduleManager.tsx
  src/pages/Login/LoginApi.tsx
  src/pages/Login/index.tsx
  src/pages/Login/setupAxiosInterceptors.ts
Labels: design, feature, chore

#50 [main] 메인 페이지 API & 라우팅 처리
  package-lock.json
  package.json
  src/api/fetch.ts
  src/api/schema.d.ts
  src/api/type.ts
  src/common/hooks/useFetch.ts
  src/common/styles/theme.ts
  src/common/utils/delayExecution.ts
  src/common/utils/formatDate.ts
  src/components/assets/images/GoogleMap.svg
  src/components/card/MyPlannerCard.tsx
  src/components/cardList/MyPlannerCardList.tsx
  src/components/chat/ChatProfile.tsx
  src/components/debug/TokenCookieManager.tsx
  src/components/modal/Modal.tsx
  src/components/modal/ModalLayout.tsx
  src/pages/Main/api/getRoomList.ts
  src/pages/Main/containers/MyPlannerCardListContainer.tsx
  src/pages/Main/containers/StartPlannerCardContainer.tsx
  src/pages/Modal/RoomCreateModal.tsx
  src/pages/Modal/RoomEnterModal.tsx
  src/pages/Modal/api/createRoom.ts
  src/pages/Modal/api/enterRoom.ts
  src/pages/Modal/containers/RoomCreateModalContainer.tsx
  src/pages/Modal/containers/RoomEnterModalContainer.tsx
  src/routes/type.ts
  tsconfig.app.json
  vite.config.ts
Labels: feature

#51 [planner] 플래너 웹소켓 작업
  .env.template
  package-lock.json
  package.json
  src/api/fetch.ts
  src/common/services/WebSocketClient.ts
  src/components/button/PlanButtons.tsx
  src/components/button/SettingButton.stories.tsx
  src/components/button/SettingButton.tsx
  src/pages/Login/index.tsx
  src/pages/Planner/SampleWS.tsx
  src/pages/Planner/index.tsx
  src/vite-env.d.ts
  vite.config.ts
Labels: fix, feature

#56 [map] 지도 페이지 컴포넌트 병합
  src/common/styles/GlobalStyle.tsx
  src/components/cardList/RouteCardList.tsx
  src/components/section/ScheduleManager.tsx
  src/pages/Planner/components/MapComponent.tsx
  src/pages/Planner/index.tsx
Labels: feature

#55 [login] 로그인 기능 완성, protected route 적용
  package-lock.json
  src/api/fetch.ts
  src/main.tsx
  src/pages/Login/index.tsx
  src/pages/Login/setupAxiosInterceptors.ts
  src/pages/Modal/api/enterRoom.ts
  src/pages/Planner/components/MapComponent.tsx
  src/pages/Planner/components/ScheduleApi.ts
  src/pages/Planner/components/ScheduleManager.stories.tsx
  src/pages/Planner/components/ScheduleManager.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/index.tsx
Labels: fix, feature

#57 [planner, chat] 플래너 웹소켓 작업
  src/common/styles/GlobalStyle.tsx
  src/common/styles/scrollbarStyle.ts
  src/components/card/StartPlannerCard.tsx
  src/components/chat/ChatInfoBar.tsx
  src/components/chat/ChatList.tsx
  src/components/debug/TokenCookieManager.tsx
  src/components/searchresultlist/SearchResultList.tsx
  src/pages/Planner/containers/ChatContainer.tsx
  src/pages/Planner/hooks/useUserProfile.ts
  src/pages/Planner/hooks/useWebSocketChat.ts
Labels: design, feature

#59 [map, main] 충돌로 인한 코드 중복 삭제
  src/pages/Planner/components/MapComponent.tsx
  src/routes/index.tsx
Labels: fix

#61 [schedule] 일정 관리 API 1차 적용, 상세 팝업 구성
  package-lock.json
  src/common/services/WebSocketClient.ts
  src/components/assets/icons/closebutton.svg
  src/components/button/Button.stories.tsx
  src/components/button/PlanButtons.stories.tsx
  src/components/button/ScheduleBar.stories.tsx
  src/components/button/mockSchedule.ts
  src/components/card/InfoCard.stories.tsx
  src/components/card/InfoCard.tsx
  src/components/card/RouteCard.stories.tsx
  src/components/cardList/RouteCardList.stories.tsx
  src/components/cardList/RouteCardList.tsx
  src/components/schedule/DetailPopup.tsx
  src/components/schedule/InfoCard.tsx
  src/components/schedule/PlanButtons.tsx
  src/components/schedule/RouteCard.tsx
  src/components/schedule/RouteCardList.tsx
  src/components/schedule/ScheduleBar.tsx
  src/pages/Planner/components/ScheduleManager.stories.tsx
  src/pages/Planner/components/ScheduleManager.tsx
  src/pages/Planner/hooks/ScheduleWS.tsx
  src/routes/index.tsx
Labels: feature, chore

#64 [chat] 웹소켓 시스템 중복 구독 문제 & 타이밍 이슈 수정
  src/common/hooks/useWebSocket.ts
  src/common/hooks/useWebSocketClient.ts
  src/common/hooks/useWebSocket_.ts
  src/common/provider/WebSocketContext.ts
  src/common/provider/WebSocketProvider.tsx
  src/common/services/WebSocketClient.ts
  src/common/services/WebSocketClient_.ts
  src/common/utils/getTokenString.ts
  src/pages/Planner/SampleWS.tsx
  src/pages/Planner/containers/ChatContainer.tsx
  src/pages/Planner/hooks/ScheduleWS.tsx
  src/pages/Planner/hooks/useWebSocketChat.ts
  src/pages/Planner/hooks/useWebSocketMapMarkers.ts
  src/pages/Planner/hooks/useWebSocketMembers.ts
  src/pages/Planner/hooks/useWebSocketSchedules.ts
  src/pages/Planner/index.tsx
Labels: fix

#65 [schedule]: 일정관리 수정, 삭제 기능 구현
  src/common/services/WebSocketClient.ts
  src/components/button/mockSchedule.ts
  src/components/schedule/DetailPopup.tsx
  src/components/schedule/InfoCard.stories.tsx
  src/components/schedule/PlanButtons.stories.tsx
  src/components/schedule/RouteCard.stories.tsx
  src/components/schedule/RouteCard.tsx
  src/components/schedule/RouteCardList.stories.tsx
  src/components/schedule/RouteCardList.tsx
  src/components/schedule/ScheduleBar.stories.tsx
  src/components/schedule/ScheduleBar.tsx
  src/pages/Planner/components/ScheduleApi.ts
  src/pages/Planner/components/ScheduleManager.stories.tsx
  src/pages/Planner/components/ScheduleManager.tsx
  src/pages/Planner/hooks/ScheduleWS.tsx
Labels: fix, feature, refactor

#67 [ planner] 캘린더 상호작용 이슈 수정 & 플래너 프로세스 개선
  src/common/hooks/useWebSocket.ts
  src/components/chat/ChatList.tsx
  src/components/modal/BackgroundModal.tsx
  src/pages/Main/index.tsx
  src/pages/Modal/CreateRoomModal.tsx
  src/pages/Planner/containers/ChatContainer.tsx
  src/pages/Planner/hooks/useWebSocketMembers.ts
Labels: fix, feature, refactor

#68 [fix] 렌더링 타이밍 버그 해결
  src/components/schedule/PlanButtons.tsx
  src/components/schedule/RouteCard.tsx
  src/components/schedule/RouteCardList.tsx
  src/pages/Planner/components/ScheduleManager.tsx
  src/pages/Planner/hooks/ScheduleWS.tsx
Labels: fix, refactor

#69 [map] 지도 마커 웹소켓 연결
  src/components/profile/Profile.tsx
  src/pages/Planner/components/MapComponent.tsx
  src/pages/Planner/components/ScheduleManager.tsx
  src/pages/Planner/hooks/useWebSocketChat.ts
  src/pages/Planner/hooks/useWebSocketMapMarkers.ts
Labels: feature, chore

#70 [auth, planner] 로그인 헤더 상태 동기화 & 캘린더 수정
  index.html
  src/api/authLocalStorage.ts
  src/common/hooks/useAuth.ts
  src/common/hooks/useWebSocket.ts
  src/common/provider/AuthContext.ts
  src/common/provider/AuthContext.tsx
  src/common/styles/GlobalStyle.tsx
  src/common/utils/getTokenString.ts
  src/common/utils/localStorageHelper.ts
  src/components/chat/ChatInput.tsx
  src/components/debug/TokenCookieManager.tsx
  src/components/modal/Modal.tsx
  src/main.tsx
  src/pages/Login/index.tsx
  src/pages/Login/setupAxiosInterceptors.ts
  src/pages/Modal/api/enterRoom.ts
  src/pages/My/index.tsx
  src/routes/ProtectedRoute.tsx
Labels: fix, feature

#72 [chat] 채팅 입력 불일치 수정 & 웹소켓 요청 경로 수정
  src/common/hooks/useWebSocket.ts
  src/components/chat/ChatInput.tsx
Labels: fix

#74 [map] 지도 마커 웹소켓 3차 구현
  src/components/assets/images/NormalMarkerImage.svg
  src/components/assets/images/NormalMarkerImage.tsx
  src/components/normalmarker/NormalMarker.tsx
  src/pages/Planner/components/MapComponent.tsx
  src/pages/Planner/components/ScheduleManager.tsx
  src/pages/Planner/hooks/useWebSocketMapMarkers.ts
Labels: feature, chore

#75 [deploy]: vercel 배포 구성 파일 추가
  .gitignore
  src/common/styles/GlobalStyle.tsx
  vercel.json
  vite.config.ts
Labels: chore

#77 [map] 지도 마커 웹소켓 최종 구현
  src/pages/Planner/components/MapComponent.tsx
  src/pages/Planner/components/ScheduleManager.tsx
Labels: feature, chore

#78 [schedule] 버그 수정 완료
  src/components/schedule/InfoCard.tsx
  src/components/schedule/RouteCard.tsx
  src/components/schedule/RouteCardList.tsx
  src/pages/Main/index.tsx
  src/pages/Planner/components/ScheduleManager.tsx
  src/routes/ProtectedRoute.tsx
Labels: fix, feature, refactor

#79 [chore] 환경변수 처리
  src/pages/Login/index.tsx
Labels: chore
